spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro_order
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  spring:
    security:
      enabled: false

  application:
    name: order-service

server:
  port: 9092
  servlet:
    context-path: /order-service

application:
  config:
    trace: true
